---
title: "Roto Draft Prep"
author: "Tom Kain"
date: "3/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

Data from [Fangraphs](https://www.fangraphs.com/fantasy-tools/auction-calculator?teams=12&lg=MLB&dollars=1000&mb=1&mp=20&msp=5&mrp=5&type=bat&players=&proj=fangraphsdc&split=&rep=0&drp=0&pp=C,SS,2B,3B,OF,1B&pos=1,1,1,1,3,1,0,0,0,1,5,3,0,8,0&sort=&view=0&points=c|1,2,3,4,5,6|1,2,3,4)
```{r}

batting <-
  here::here("in", "fangraphs-auction-calculator-batting.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  select(name, team, pos, adp, pts, a_pos, dollars, player_id)

pitching <-
  here::here("in", "fangraphs-auction-calculator-pitching.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  select(name, team, pos, adp, pts, a_pos, dollars, player_id)

rankings <- 
  batting %>% 
  bind_rows(pitching) %>% 
  arrange(dollars %>% desc) %>% 
  head(400) %>% 
  mutate(pos_primary = str_extract(pos, '^[^/]+'))

```

```{r}

rankings %>% 
  filter(adp < 999) %>% 
  ggplot(aes(x=adp,y=dollars,color=pos_primary)) +
  geom_point() +
  geom_smooth(aes(group=1), method = "lm")

rankings %>% 
  filter(adp < 999) %>% 
  ggplot(aes(x=adp,y=dollars)) +
  geom_point() +
  geom_smooth(aes(group=1), method = "lm") + 
  facet_wrap(~pos_primary)

```

```{r Write Output}

output <-
  rankings %>% 
  mutate(adp_round = (adp / 12) %>% ceiling(),
         adp = adp %>% round(),
         rank = row_number(),
         dollars = dollars %>% round()) %>% 
  select(name, pos_primary, adp_round, rank, dollars)

output %>% 
  write_csv(here::here("out", "fb_roto_2021.csv"))

```