---
title: "Draft Results"
author: "Tom Kain"
date: "March 24, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
knitr::opts_knit$set(stop_on_error = 2L)
source("R/yahoo_api.R")
source("R/z_scores.R")
options(tidyverse.quiet=TRUE)
library(knitr)
library(janitor)
library(tidyverse)
```

# Data Set
Put together the data set:
1. Player
2. Position
3. Team
4. Pick
5. isKeeper

```{r}
keepers <- c(
  "Justin Turner",
  "Miles Mikolas",
  "Whit Merrifield",
  "Archie Bradley",
  "Patrick Corbin",
  "Matt Carpenter",
  "Blake Treinen",
  "Ronald Acuna Jr.",
  "Blake Snell",
  "Lorenzo Cain",
  "Trevor Story",
  "Andrew Benintendi",
  "Mike Clevinger"
)

results <- read_tsv("data/draftResults.tsv") %>%  
  clean_names() %>% 
  mutate(name = chartr("áéóíñú", "aeoinu", player)) %>% 
  select(-mlb_team, -player) %>% 
  mutate(keeper = (name %in% keepers)) 

ranks <- readRDS("data/draft_dataset_with_keepers") %>% 
  clean_names() %>% 
  select(name, adp, z_sum, z_rank)

results <- results %>%
  left_join(ranks, by = "name")

```

# My team
How did I do? 

# Team Scores
Compute z_scores based on my pre-draft rankings

# z_Rank vs ADP
See biggest stretches vs biggest value gets - what does that say about our league?

# Consider preseason trades
```{r}
results %>% 
  filter(grepl("Plouffe|Hebrew",team)) %>% 
  arrange(team, z_sum %>% desc) %>%
  View()
```