---
title: "Draft Research pt1"
author: "Tom Kain"
date: "February 20, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("R/yahoo_api.R")
library(tidyverse)
```

# Position Eligibility
```{r}
(get_players(50) -> tst_results)

tst_results %>% saveRDS("data/tst_results")

```
Two ways avenues with which I'm hoping to find a solution with at least one. 
```{r}
# get all positions per row as list, add to data set
tst_results %>%
  select(starts_with("eligible_positions")) %>%
  transpose() %>%
  lapply(as.character) %>%
  lapply(function(x) x[!is.na(x)]) -> pos_complete

tst_results %>%
  add_column(all_pos = pos_complete) %>%
  # Challenge - results stord as a list type column, need to convert to a character vector with ", " separator.
  select(1, all_pos)

```

```{r}
# rather than store as list, complete the paste of the various columns directly
collapse_cols <- function(d,...) {
  vars  <- quos(...)
  d %>% mutate(f = paste(!!!vars, sep=", "))
}

# this works, but isn't dynamic based on the potentially varying number of eligible position columns
tst_results %>%
  select(starts_with("eligible_positions")) %>%
  mutate(all_pos = paste(eligible_positions.position,
                         eligible_positions.position.1, sep = ", ")) %>%
  select(1,2, all_pos) %>%
  head()

col_nms <- tst_results %>%
  select(starts_with("eligible_positions")) %>%
  colnames()

# challenge - pass the dynamic list of column names to the paste function
tst_results %>%
  collapse_cols(col_nms) %>%
  select(f) %>%
  head()

tst_results %>%
  mutate(all_pos = paste(quos(eligible_positions.position, eligible_positions.position.1), sep=", ")) %>%
  select(all_pos)
```
         
