---
title: "Optimal Lineup"
author: "Tom Kain"
date: "July 6, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
library(plotly)

source("R/helper.R")
```


```{r}
rosters <- load_players_with_projections()

rosters_by_position <- row_per_position(rosters)

rosters_by_position %>% 
  filter(!is.na(manager)) %>% 
  group_by(position) %>% 
  count() %>% 
  ungroup() -> rostered_count_by_pos

rosters_by_position %>% 
  group_by(position) %>% 
  arrange(zar %>% desc()) %>% 
  mutate(num = row_number()) %>% 
  full_join(rostered_count_by_pos, "position") %>% 
  filter(num <= n) %>% 
  summarize(median_zar = median(zar)) -> pos_median_zar

rosters_by_position %>% 
  full_join(pos_median_zar) %>% 
  #FIXME two decimal places for pos_zar
  mutate(pos_zar = zar - median_zar) -> rosters_by_position

team <- rosters_by_position %>% 
  filter(team == "Plouffe There It Is!")

positions <- c("C","1B","2B","3B","SS","LF","CF","RF","Util")

```


```{r}
batters <- team %>%
  filter(type == "batter") %>% 
  select(player_id, name_full, position, pos_zar, zar) %>% 
  arrange(zar %>% desc(), pos_zar %>% desc) 
  

batter_ids <- batters$player_id %>% 
  as_factor() %>%
  levels()

team_result <- tibble(
  position = positions,
  player_id = NA
)

i <- 1

```
```{r}

batter_id <- batter_ids[i]

batter <- batters %>% 
  filter(player_id == batter_id)

batters <- batters %>% 
  add_row(
    player_id = batter$player_id[1],
    name_full = batter$name_full[1],
    position = "Util",
    pos_zar = -100,
    zar = batter$zar[1]
  ) %>% 
  arrange(zar %>% desc(), pos_zar %>% desc)

for (j in 1:length(batter$position)) {
  if (team_result$player_id[team_result$position == batter$position[j]] %>% is.na()) {
    team_result$player_id[team_result$position == batter$position[j]] <- batter_id
    print(paste0("Assigned ",batter_id," to ",batter$position[j]))
    break
  }
}

if (!batter_id %in% (team_result$player_id %>% as_factor() %>% levels())) {
  if (team_result$player_id[team_result$position == "Util"] %>% is.na()) {
    team_result$player_id[team_result$position == "Util"] <- batter_id
  }
  else {
    print(paste0("sending batter_id ", batter_id, " to bench"))
  }
}

i <- i+1

team_result %>% 
  left_join(batters, c("player_id","position"))
```
