---
title: "Roster Review (Generic)"
author: "Tom Kain"
date: "April 25, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
library(plotly)

source("R/helper.R")
```


```{r get_data}
force_fetch <- TRUE
force_join <- TRUE
batter_file <- "temp/FanGraphs Leaderboard.csv"
pitcher_file <- "temp/FanGraphs Leaderboard (1).csv"

if (force_fetch && (batter_file %>% is.null() || pitcher_file %>% is.null())) {
  stop("Need projection files to force a recalc")
} else {
  rosters <- load_players_with_projections(force_fetch, 
                                           force_join, 
                                           batter_file, 
                                           pitcher_file)
}
```

```{r df_prep}
rosters_by_position <- row_per_position(rosters)

team_batters_starters <- rosters_by_position %>% 
  optimal_lineup()

# TODO consider DL?
# FIXME a few empty position slots for a one or two teams
rosters_by_position %>% 
  filter(team != "Free Agent",
         type == "pitcher") %>% 
  mutate(position = as.character(position)) %>% 
  droplevels() -> team_pitchers_all

team_pitchers_SP <- team_pitchers_all %>% 
  filter(position == 'SP')

team_pitchers_RP <- team_pitchers_all %>% 
  filter(position == 'RP') %>% 
  anti_join(team_pitchers_SP, "player_id") %>% 
  group_by(team) %>% 
  arrange(zar %>% desc) %>% 
  mutate(rnk = row_number()) %>% 
  filter(rnk <= 6)

team_pitchers_SP %>% 
  bind_rows(team_pitchers_RP) %>% 
  select(position, player_id, name_full, team, manager, zar, pos_zar) -> team_pitchers_starters

rosters_by_position %>% 
  filter(team != "Free Agent",
         type == "batter") %>% 
  mutate(position = as.character(position)) %>% 
  droplevels() -> team_batters_all

team_batters_all %>% 
  anti_join(team_batters_starters, "player_id") %>% 
  group_by(player_id, name_full) %>% 
  arrange(player_id, pos_zar %>% desc) %>% 
  mutate(rnk = row_number(),
         position = "BN") %>% 
  filter(rnk == 1) %>% 
  ungroup() %>% 
  select(position, player_id, name_full, team, manager, zar, pos_zar) -> team_batters_bench

team_lineups <- team_batters_starters %>% 
  bind_rows(team_batters_bench) %>% 
  bind_rows(team_pitchers_starters) %>% 
  mutate(position = fct_relevel(position, "C","1B","2B","3B","SS","LF","CF","RF", "Util","SP","RP","BN"))

standings_projected <- team_lineups %>% 
  filter(position != 'BN') %>% 
  group_by(team) %>% 
  summarize(sum_pos_zar = sum(pos_zar),
            mean_pos_zar = mean(pos_zar),
            median_pos_zar = median(pos_zar),
            var_pos_zar = sd(pos_zar)) %>% 
  mutate(adj_sum_pos_zar = sum_pos_zar - median(sum_pos_zar)) %>% 
  arrange(sum_pos_zar %>% desc)

```

```{r myteam}
rosters %>% 
  filter(grepl("Plouffe",team)) %>% 
  select(name_full, positions, zar) %>% 
  arrange(zar %>% desc) %>% 
  View("My Team")
```

```{r ros_team_rankings}
# TODO adjust for DL
rosters_by_position %>% 
  filter(team != "Free Agent") %>% 
  mutate(zar = round(zar,2)) %>% 
  ggplot(aes(position, pos_zar, color = position, alpha = zar)) +
  geom_point(aes(text=name_full)) +
  facet_wrap(~ team) -> team_pos_adj

ggplotly(team_pos_adj)

team_lineups %>%
  mutate(zar = round(zar,2)) %>% 
  ggplot(aes(position, pos_zar, color = position, alpha = zar)) +
  geom_point(aes(text=name_full)) +
  facet_wrap(~ team) -> team_pos_optimal

ggplotly(team_pos_optimal)

# FIXME pretty sure this error bar ain't right
standings_projected %>% 
  mutate(team = fct_reorder(team, adj_sum_pos_zar)) %>% 
  ggplot(aes(team, adj_sum_pos_zar)) +
  geom_col() +
  geom_errorbar(aes(ymin=adj_sum_pos_zar-var_pos_zar, ymax=adj_sum_pos_zar+var_pos_zar), width = .5) +
  coord_flip()
```

```{r free_agents}
#TODO abstract some of these views
rosters %>% 
  mutate(zar = round(zar)) %>% 
  filter((team == 'Free Agent' & zar >=0) | (grepl("Plouffe",team) & zar < 3)) %>% 
  ggplot(aes(x=team,y=zar,color=type)) +
  geom_jitter(aes(text=glue("{name_full} - {display_position}", color=type)), width=.3) +
  coord_flip() -> pa

ggplotly(pa)

free_agent_compare <- 
  rosters %>% 
  filter((team == 'Free Agent' & zar >=0) | (grepl("Plouffe",team) & zar < 3)) %>% 
  arrange(zar %>% desc) %>% 
  mutate(zar = zar %>% round(digits=1))

free_agent_compare %>% 
  # select(team, name_full, positions, type, zar) %>% 
  select(team, name_full, positions, type, zar, g:war, z_r:z_whip) %>% 
  View("Available Free Agents Expanded")
  
free_agent_compare %>% 
  select(team, name_full, positions, type, zar) %>%
  View("Available Free Agents")
```

```{r trade_eval}
# TODO find way to wrap these three views into one
rosters_by_position %>% 
  filter(grepl("Plouffe|Bumpin",team)) %>% 
  select(team, manager, name_full, display_position, zar, pos_zar, positions, draft_round) %>% 
  arrange(zar %>% desc) %>% 
  mutate(zar = zar %>% round(1)) %>% 
  View("Trade Partner")
  # mutate(zar = janitor::round_half_up(zar)) %>% 
  # write_csv("data/tradeReview_20190423.csv")

rosters %>% 
  filter(grepl("Plouffe|Bumpin",team)) %>% 
  ggplot(aes(x=team,y=zar,color=type)) +
  geom_jitter(aes(text=glue("{name_full} - {display_position}", color=type)), width=.2) +
  coord_flip() -> tv

ggplotly(tv)

rosters %>% 
  #filter(grepl("Plouffe|Oakmont|Nuts",team)) %>% 
  select(team, manager, name_full, display_position, zar) %>% 
  filter(grepl("Benintendi|Martin Perez",name_full)) 
# %>%
#   group_by(team) %>%
#   summarize(zar = sum(zar))
```

```{r draft_analysis}
#TODO measuring projected value of draft picks, move to separate research
#TODO get beginning of year zar/war values
rosters %>% 
  filter(!is.na(draft_pick)) %>%
  group_by(draft_round) %>% 
  summarize(zar_median = median(zar) %>% janitor::round_half_up(),
            zar_mean = mean(zar) %>% janitor::round_half_up()) %>%
  ggplot(aes(x=draft_round,y=zar_mean)) +
  geom_col() +
  geom_line(aes(y=zar_median)) -> draft_plot

ggplotly(draft_plot)

rosters %>% 
  filter(!is.na(draft_pick)) %>% 
  group_by(draft_round) %>% 
  arrange(draft_round) %>% 
  ggplot(aes(x=draft_round,y=zar,group=draft_round)) +
  geom_boxplot()

rosters %>% 
  filter(!is.na(draft_pick)) %>%
  group_by(draft_round) %>% 
  summarize(war_median = median(war) %>% janitor::round_half_up(),
            war_mean = mean(war) %>% janitor::round_half_up()) %>%
  ggplot(aes(x=draft_round,y=war_mean)) +
  geom_col() +
  geom_line(aes(y=war_median)) -> draft_plot_war

ggplotly(draft_plot_war)

rosters %>% 
  filter(!is.na(draft_pick)) %>% 
  group_by(draft_round) %>% 
  arrange(draft_round) %>% 
  ggplot(aes(x=draft_round,y=war,group=draft_round)) +
  geom_boxplot()

# frequency graph by pos_zar for each position
rosters_by_position %>% 
  filter(team != "Free Agent") %>% 
  ggplot(aes(pos_zar)) + 
  geom_freqpoly(binwidth=.25) + 
  facet_wrap(~ position)
```

```{r dups}
#FIXME dups 
rosters %>% count(player_id) %>% filter(n > 1) %>% left_join(rosters) -> dups

dups %>% count(team)

dups %>% select(team, manager, name_full, positions)

```